#Expyriment 0.11.dev5 (Python 3.12.0), .xpe-file, coding: UTF-8
#date: Wed Oct 16 2024 15:45:41
#sha1: 4afe66
#modules: 
#display: size=(800, 600), window_mode=True, opengl=2
#os: uname_result(system='Linux', node='is154920', release='6.8.0-45-lowlatency', version='#45.1~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Sep  6 15:26:10 UTC', machine='x86_64')
Time,Type,Event,Value,Detail,Detail2
425,stderr,received,'Traceback (most recent call last):'
425,stderr,received,'  File "/home/cp983411/00_git/ppe/experiments/kinematogram/kine.py", line 19, in <module>'
425,stderr,received,'    k = RandomDotKinematogram(200, 100, (10,0), .1)'
426,stderr,received,'        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'
426,stderr,received,'  File "/home/cp983411/.pyenv/versions/expyriment-py3.12-0.11.0.dev3/.expyriment/extras/expyriment_stimuli_extras/randomdotkinematogram/__init__.py", line 67, in __init__'
426,stderr,received,'    RandomDotKinematogram.__init__(self, area_radius, n_dots,'
426,stderr,received,'  File "/home/cp983411/.pyenv/versions/expyriment-py3.12-0.11.0.dev3/.expyriment/extras/expyriment_stimuli_extras/randomdotkinematogram/_randomdotkinematogram.py", line 83, in __init__'
426,stderr,received,'    self.reset(n_dots=n_dots, target_direction=target_direction,'
426,stderr,received,'  File "/home/cp983411/.pyenv/versions/expyriment-py3.12-0.11.0.dev3/.expyriment/extras/expyriment_stimuli_extras/randomdotkinematogram/_randomdotkinematogram.py", line 105, in reset'
427,stderr,received,'    self.target_dot_ratio = target_dot_ratio'
427,stderr,received,'    ^^^^^^^^^^^^^^^^^^^^^'
427,stderr,received,'  File "/home/cp983411/.pyenv/versions/expyriment-py3.12-0.11.0.dev3/.expyriment/extras/expyriment_stimuli_extras/randomdotkinematogram/_randomdotkinematogram.py", line 156, in target_dot_ratio'
428,stderr,received,'    d = self._make_random_dot(direction=self.target_direction, randomize_age=True)'
428,stderr,received,'        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^'
428,stderr,received,'  File "/home/cp983411/.pyenv/versions/expyriment-py3.12-0.11.0.dev3/.expyriment/extras/expyriment_stimuli_extras/randomdotkinematogram/_randomdotkinematogram.py", line 182, in _make_random_dot'
429,stderr,received,'    rtn = MovingPosition(position=pos,'
429,stderr,received,'          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^'
429,stderr,received,'  File "/home/cp983411/.pyenv/versions/expyriment-py3.12-0.11.0.dev3/.expyriment/extras/expyriment_stimuli_extras/randomdotkinematogram/_randomdotkinematogram.py", line 315, in __init__'
430,stderr,received,'    self._update_movement_vector()'
430,stderr,received,'  File "/home/cp983411/.pyenv/versions/expyriment-py3.12-0.11.0.dev3/.expyriment/extras/expyriment_stimuli_extras/randomdotkinematogram/_randomdotkinematogram.py", line 379, in _update_movement_vector'
430,stderr,received,'    direction = 450 - self._direction'
431,stderr,received,'                ~~~~^~~~~~~~~~~~~~~~~'
431,stderr,received,"TypeError: unsupported operand type(s) for -: 'int' and 'tuple'"
